version: '3'
services:
  registry:
    container_name: registry
    image: registry:2.8
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_STORAGE_DELETE_ENABLED: true
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data/registry
    ports:
      - 5000:5000
    volumes:
      - ./auth:/auth
      - ./data:/data/registry
    restart: always
